// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'api/model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 6480868385427421829),
      name: 'BikeOilEntry',
      lastPropertyId: const IdUid(4, 1104671193688755175),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2204096706384795893),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 6813696554359304607),
            name: 'date',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 2290763666080558549),
            name: 'meter',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1104671193688755175),
            name: 'litre',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 6480868385427421829),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    BikeOilEntry: EntityDefinition<BikeOilEntry>(
        model: _entities[0],
        toOneRelations: (BikeOilEntry object) => [],
        toManyRelations: (BikeOilEntry object) => {},
        getId: (BikeOilEntry object) => object.id,
        setId: (BikeOilEntry object, int id) {
          object.id = id;
        },
        objectToFB: (BikeOilEntry object, fb.Builder fbb) {
          final dateOffset = fbb.writeString(object.date);
          final meterOffset = fbb.writeString(object.meter);
          final litreOffset = fbb.writeString(object.litre);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, dateOffset);
          fbb.addOffset(2, meterOffset);
          fbb.addOffset(3, litreOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = BikeOilEntry(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              date: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              meter: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              litre: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [BikeOilEntry] entity fields to define ObjectBox queries.
class BikeOilEntry_ {
  /// see [BikeOilEntry.id]
  static final id =
      QueryIntegerProperty<BikeOilEntry>(_entities[0].properties[0]);

  /// see [BikeOilEntry.date]
  static final date =
      QueryStringProperty<BikeOilEntry>(_entities[0].properties[1]);

  /// see [BikeOilEntry.meter]
  static final meter =
      QueryStringProperty<BikeOilEntry>(_entities[0].properties[2]);

  /// see [BikeOilEntry.litre]
  static final litre =
      QueryStringProperty<BikeOilEntry>(_entities[0].properties[3]);
}
